-- =====================================================
-- 07_analytics_views.sql
-- Banking Analytics Views
-- =====================================================

USE DATABASE BANKING_DB;
USE SCHEMA ANALYTICS;

----------------------------------------------------------
-- CUSTOMER 360
----------------------------------------------------------

CREATE OR REPLACE VIEW CUSTOMER_360 AS

SELECT

C.CUSTOMER_ID,
C.FIRST_NAME,
C.LAST_NAME,
C.GENDER,
C.AGE,
C.COUNTRY,
C.CITY,
C.OCCUPATION,
C.ANNUAL_INCOME,
C.CUSTOMER_SEGMENT,
C.RISK_PROFILE,
C.KYC_STATUS,

COUNT(DISTINCT A.ACCOUNT_ID) TOTAL_ACCOUNTS,

COUNT(T.TRANSACTION_ID) TOTAL_TRANSACTIONS,

SUM(T.AMOUNT) TOTAL_TRANSACTION_AMOUNT,

AVG(T.AMOUNT) AVG_TRANSACTION_AMOUNT,

SUM(A.CURRENT_BALANCE) CURRENT_BALANCE

FROM RAW.CUSTOMERS C

LEFT JOIN RAW.ACCOUNTS A
ON C.CUSTOMER_ID=A.CUSTOMER_ID

LEFT JOIN RAW.TRANSACTIONS T
ON A.ACCOUNT_ID=T.ACCOUNT_ID

GROUP BY

C.CUSTOMER_ID,
C.FIRST_NAME,
C.LAST_NAME,
C.GENDER,
C.AGE,
C.COUNTRY,
C.CITY,
C.OCCUPATION,
C.ANNUAL_INCOME,
C.CUSTOMER_SEGMENT,
C.RISK_PROFILE,
C.KYC_STATUS;

----------------------------------------------------------
-- BRANCH PERFORMANCE
----------------------------------------------------------

CREATE OR REPLACE VIEW BRANCH_PERFORMANCE AS

SELECT

B.BRANCH_ID,

B.BRANCH_NAME,

B.COUNTRY,

B.CITY,

COUNT(DISTINCT C.CUSTOMER_ID) CUSTOMERS,

COUNT(DISTINCT A.ACCOUNT_ID) ACCOUNTS,

COUNT(T.TRANSACTION_ID) TRANSACTIONS,

SUM(T.AMOUNT) TRANSACTION_AMOUNT,

AVG(A.CURRENT_BALANCE) AVG_BALANCE

FROM RAW.BRANCHES B

LEFT JOIN RAW.CUSTOMERS C
ON B.BRANCH_ID=C.BRANCH_ID

LEFT JOIN RAW.ACCOUNTS A
ON C.CUSTOMER_ID=A.CUSTOMER_ID

LEFT JOIN RAW.TRANSACTIONS T
ON A.ACCOUNT_ID=T.ACCOUNT_ID

GROUP BY

B.BRANCH_ID,
B.BRANCH_NAME,
B.COUNTRY,
B.CITY;

----------------------------------------------------------
-- COUNTRY PERFORMANCE
----------------------------------------------------------

CREATE OR REPLACE VIEW COUNTRY_PERFORMANCE AS

SELECT

COUNTRY,

COUNT(DISTINCT CUSTOMER_ID) CUSTOMERS,

COUNT(DISTINCT ACCOUNT_ID) ACCOUNTS,

COUNT(*) TRANSACTIONS,

SUM(AMOUNT) TOTAL_AMOUNT,

AVG(AMOUNT) AVG_AMOUNT

FROM RAW.TRANSACTIONS

GROUP BY COUNTRY;

----------------------------------------------------------
-- TRANSACTION ANALYTICS
----------------------------------------------------------

CREATE OR REPLACE VIEW TRANSACTION_ANALYTICS AS

SELECT

DATE_TRUNC('MONTH',TRANSACTION_TIMESTAMP) MONTH,

TRANSACTION_TYPE,

TRANSACTION_CHANNEL,

COUNT(*) TOTAL_TRANSACTIONS,

SUM(AMOUNT) TOTAL_AMOUNT,

AVG(AMOUNT) AVG_AMOUNT

FROM RAW.TRANSACTIONS

GROUP BY

DATE_TRUNC('MONTH',TRANSACTION_TIMESTAMP),

TRANSACTION_TYPE,

TRANSACTION_CHANNEL;

----------------------------------------------------------
-- HIGH VALUE CUSTOMERS
----------------------------------------------------------

CREATE OR REPLACE VIEW HIGH_VALUE_CUSTOMERS AS

SELECT *

FROM CUSTOMER_360

WHERE CURRENT_BALANCE>100000

OR TOTAL_TRANSACTION_AMOUNT>100000;

----------------------------------------------------------
-- EXECUTIVE SUMMARY
----------------------------------------------------------

CREATE OR REPLACE VIEW EXECUTIVE_SUMMARY AS

SELECT

(SELECT COUNT(*) FROM RAW.CUSTOMERS) TOTAL_CUSTOMERS,

(SELECT COUNT(*) FROM RAW.ACCOUNTS) TOTAL_ACCOUNTS,

(SELECT COUNT(*) FROM RAW.TRANSACTIONS) TOTAL_TRANSACTIONS,

(SELECT SUM(AMOUNT) FROM RAW.TRANSACTIONS) TOTAL_TRANSACTION_AMOUNT,

(SELECT AVG(AMOUNT) FROM RAW.TRANSACTIONS) AVG_TRANSACTION_AMOUNT,

(SELECT COUNT(*) FROM RAW.BRANCHES) TOTAL_BRANCHES;