USE DATABASE BANKING_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW FRAUD_ANALYTICS AS

SELECT

    T.TRANSACTION_ID,
    T.ACCOUNT_ID,
    A.CUSTOMER_ID,

    C.BRANCH_ID,
    C.COUNTRY,
    C.CITY,

    T.TRANSACTION_TIMESTAMP,
    T.TRANSACTION_TYPE,
    T.TRANSACTION_CHANNEL,
    T.AMOUNT,

    T.IS_FRAUD,
    T.FRAUD_SCORE,
    T.FRAUD_REASON

FROM RAW.TRANSACTIONS T

LEFT JOIN RAW.ACCOUNTS A
ON T.ACCOUNT_ID = A.ACCOUNT_ID

LEFT JOIN RAW.CUSTOMERS C
ON A.CUSTOMER_ID = C.CUSTOMER_ID;